// Canonical tenancy field mapping profile for the DLD/Ejari-style template
// shared by the Tenancy Contract Builder module.

export const TENANCY_TEMPLATE_PROFILE_V1 = {
  profileId: 'dld-ejari-v1',
  label: 'DLD Ejari Tenancy Contract (3-page bilingual)',
  templateType: 'both', // fillable | static | both
  // For fillable templates this can map to actual AcroForm field names.
  // For static templates this maps business keys to known template labels,
  // then a coordinate profile can be layered in next phase.
  fields: [
    {
      id: 'date',
      path: 'property.documentDate',
      section: 'contract',
      labelEn: 'Date',
      labelAr: 'التاريخ',
      required: true,
    },
    {
      id: 'owner-name',
      path: 'landlord.name',
      section: 'landlord',
      labelEn: "Owner's Name",
      labelAr: 'اسم المالك',
      required: true,
    },
    {
      id: 'lessor-name',
      path: 'landlord.name',
      section: 'landlord',
      labelEn: "Lessor's Name",
      labelAr: 'اسم المؤجر',
      required: true,
    },
    {
      id: 'lessor-eid',
      path: 'landlord.emiratesId',
      section: 'landlord',
      labelEn: "Lessor's Emirates ID",
      labelAr: 'الهوية الإماراتية للمؤجر',
      required: true,
    },
    {
      id: 'lessor-email',
      path: 'landlord.email',
      section: 'landlord',
      labelEn: "Lessor's Email",
      labelAr: 'البريد الإلكتروني للمؤجر',
      required: false,
    },
    {
      id: 'lessor-phone',
      path: 'landlord.phone',
      section: 'landlord',
      labelEn: "Lessor's Phone",
      labelAr: 'رقم هاتف المؤجر',
      required: false,
    },
    {
      id: 'tenant-name',
      path: 'tenant.fullName',
      section: 'tenant',
      labelEn: "Tenant's Name",
      labelAr: 'اسم المستأجر',
      required: true,
    },
    {
      id: 'tenant-eid',
      path: 'tenant.emiratesId',
      section: 'tenant',
      labelEn: "Tenant's Emirates ID",
      labelAr: 'الهوية الإماراتية للمستأجر',
      required: true,
    },
    {
      id: 'tenant-email',
      path: 'tenant.email',
      section: 'tenant',
      labelEn: "Tenant's Email",
      labelAr: 'البريد الإلكتروني للمستأجر',
      required: false,
    },
    {
      id: 'tenant-phone',
      path: 'tenant.contactNo',
      section: 'tenant',
      labelEn: "Tenant's Phone",
      labelAr: 'رقم هاتف المستأجر',
      required: false,
    },
    {
      id: 'property-plot-no',
      path: 'property.plotNo',
      section: 'property',
      labelEn: 'Plot No.',
      labelAr: 'رقم الأرض',
      required: false,
    },
    {
      id: 'property-makani-no',
      path: 'property.makaniNo',
      section: 'property',
      labelEn: 'Makani No.',
      labelAr: 'رقم مكاني',
      required: false,
    },
    {
      id: 'property-location',
      path: 'property.community',
      section: 'property',
      labelEn: 'Location',
      labelAr: 'الموقع',
      required: true,
    },
    {
      id: 'property-building-name',
      path: 'property.cluster',
      section: 'property',
      labelEn: 'Building Name',
      labelAr: 'اسم المبنى',
      required: false,
    },
    {
      id: 'property-type',
      path: 'property.propertyType',
      section: 'property',
      labelEn: 'Property Type',
      labelAr: 'نوع الوحدة',
      required: true,
    },
    {
      id: 'property-no',
      path: 'property.unit',
      section: 'property',
      labelEn: 'Property No.',
      labelAr: 'رقم العقار',
      required: true,
    },
    {
      id: 'property-area',
      path: 'property.size',
      section: 'property',
      labelEn: 'Property Area (s.m)',
      labelAr: 'مساحة العقار (متر.مربع)',
      required: false,
    },
    {
      id: 'dewa-premises-no',
      path: 'property.dewaPremisesNo',
      section: 'property',
      labelEn: 'Premises No. (DEWA)',
      labelAr: 'رقم المبنى (ديوا)',
      required: false,
    },
    {
      id: 'contract-from',
      path: 'payments.contractStartDate',
      section: 'contract',
      labelEn: 'From',
      labelAr: 'من',
      required: true,
    },
    {
      id: 'contract-to',
      path: 'payments.contractEndDate',
      section: 'contract',
      labelEn: 'To',
      labelAr: 'إلى',
      required: true,
    },
    {
      id: 'contract-value',
      path: 'payments.total',
      section: 'contract',
      labelEn: 'Contract Value',
      labelAr: 'قيمة العقد',
      required: false,
    },
    {
      id: 'annual-rent',
      path: 'payments.annualRent',
      section: 'contract',
      labelEn: 'Annual Rent',
      labelAr: 'الإيجار السنوي',
      required: true,
    },
    {
      id: 'security-deposit',
      path: 'payments.securityDeposit',
      section: 'contract',
      labelEn: 'Security Deposit Amount',
      labelAr: 'مبلغ التأمين',
      required: true,
    },
    {
      id: 'mode-of-payment',
      path: 'payments.modeOfPayment',
      section: 'contract',
      labelEn: 'Mode of Payment',
      labelAr: 'طريقة الدفع',
      required: false,
    },
  ],
};

export const getTenancyFieldProfile = () => TENANCY_TEMPLATE_PROFILE_V1;

export const getRequiredMappedFields = () =>
  TENANCY_TEMPLATE_PROFILE_V1.fields.filter((field) => field.required);
